services:
  # RabbitMQ service with Management UI
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_buffer
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: project_4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Airflow service
  airflow:
    build: .
    command: standalone
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - PYTHONPATH=/opt/airflow/workspace/src
      - DB_PATH=/opt/airflow/workspace/data/crypto_catalog.ducklake
    volumes:
      - .:/opt/airflow/workspace
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ~/.aws:/home/airflow/.aws
      - ./crypto_dbt:/opt/airflow/dags/crypto_dbt
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  metabase:
    build:
      context: .
      dockerfile: dockerfile.metabase
    ports:
      - "3000:3000"
    environment:
      # Directs Metabase to look for drivers in the mounted folder
      - MB_PLUGINS_DIR=/plugins
    volumes:
      # Mount the driver JAR file
      - ./plugins:/plugins
      # Mount your DuckLake data folder
      - ./data:/data
    restart: always

volumes:
  rabbitmq_data:
  postgres_data:
  metabase_pgdata: